
version: '2'
services:
  nginx:
     image: nginx:1.13.0
     volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.pem:/etc/ssl/certs/localhost.pem
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
     ports:
      - "443:443"
  mongo:
    image: mongo:3.3
  app-a-saml-sp:
    image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:5974f20e2058f4831a4f6e331515c1dcb43e3815
    volumes:
     - ./config:/certificates
    environment:
     - IDP_METADATA_URL=https://kkff.kvalitetsit.dk/venliglogin/saml2/idp/metadata.php
     - IDP_LOGIN_URL=https://kkff.kvalitetsit.dk/venliglogin/saml2/idp/SSOService.php  
     - CERTIFICATE=/certificates/appa.cert
     - KEY=/certificates/appa.pem
     - SP_ENTITY_ID=test:eg
     - SAML_LB_SCHEME=https           # TODO Webserver (LB), http or https
     - SAML_LB_SERVERNAME=venliglogin.careappdev.dk  # TODO Webserver (LB), servername
     - SAML_LB_SERVERPORT=443       # TODO Webserver (LB), Port
   #  - APP_CONTEXT=appa              # TODO contexten for applikationen (SAML_LB_SCHEME://SAML_LB_SERVERNAME:SAML_LB_SERVERPORT/APP_CONTEXT)
     - MONGODB=mongo
     - MONGODB_DATABASE=mongo_appa
  app-a-sp-proxy:
    image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:5974f20e2058f4831a4f6e331515c1dcb43e3815
    ports:
     - "8080:80"
    environment:
     - ENDPOINT_URL=https://demo.careappdev.dk/api/auth/venlig_login      # TODO Url på applikation (Login Adaptor), localhost/127.0.0.1 can NOT be used.  
     - SAML_URL=http://app-a-saml-sp:8080/
    # - CONTEXT=appa
     - SET_HOST_SNI=true
     - REMOVE_CONTEXT=false
     - MONGODB=mongo
     - MONGODB_DATABASE=mongo_appa
     - CORRELATION_ID=correlation-id
