
version: '2'
services:
  nginx:
     image: nginx:1.13.0
     volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.pem:/etc/ssl/certs/localhost.pem
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
     ports:
      - "443:443"
  mongo:
    image: mongo:3.3
  app-a-saml-sp:
    image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:9ec8d2fd693c640023ecddaa9344c770302b6c13
    volumes:
     - ./config:/certificates
    environment:
     - IDP_METADATA_URL=https://kkff.kvalitetsit.dk/venliglogin/saml2/idp/metadata.php
     - IDP_LOGIN_URL=https://kkff.kvalitetsit.dk/venliglogin/saml2/idp/SSOService.php  
     - CERTIFICATE=/certificates/appa.cert
     - KEY=/certificates/appa.pem
     - SP_ENTITY_ID=dev:kit:appasec
     - SAML_LB_SCHEME=https           # TODO Webserver (LB), http or https
     - SAML_LB_SERVERNAME=demo.careappdev.dk  # TODO Webserver (LB), servername
     - SAML_LB_SERVERPORT=443       # TODO Webserver (LB), Port
     - APP_CONTEXT=appa              # TODO contexten for applikationen (SAML_LB_SCHEME://SAML_LB_SERVERNAME:SAML_LB_SERVERPORT/APP_CONTEXT)
     - MONGODB=mongo
     - MONGODB_DATABASE=mongo_appa
  app-a-sp-proxy:
    image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:2cc8b2da1105dc1c405a3e349c08a844f8f95ecb
    ports:
     - "8080:80"
    environment:
     - ENDPOINT_URL=https://demo.careappdev.dk/api/auth/venlig_login      # TODO Url på applikation (Login Adaptor), localhost/127.0.0.1 can NOT be used.  
     - SAML_URL=http://app-a-saml-sp:8080/
     - CONTEXT=appa
     - REMOVE_CONTEXT=true
     - MONGODB=mongo
     - MONGODB_DATABASE=mongo_appa
     - CORRELATION_ID=correlation-id
