version: '2'
services:
   mongo:
     image: mongo:3.3
   app-a-saml-sp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:9cba176d3259deffeb9393b8efc20b78dbd215f4
     volumes:
      - ./config:/certificates 
     environment:
      - IDP_METADATA_URL=https://kkff.kvalitetsit.dk/venliglogin/saml2/idp/metadata.php
      - IDP_LOGIN_URL=https://kkff.kvalitetsit.dk/venliglogin/saml2/idp/SSOService.php  
      - CERTIFICATE=/certificates/appa.cert
      - KEY=/certificates/appa.pem
      - SP_ENTITY_ID=dev:kit:appa     
      - SAML_LB_SCHEME=http           # Webserver (LB), http or https
      - SAML_LB_SERVERNAME=localhost  # Webserver (LB), servername
      - SAML_LB_SERVERPORT=8080       # Webserver (LB), Port 
      - APP_CONTEXT=appa              # contexten for applikationen (SAML_LB_SCHEME://SAML_LB_SERVERNAME:SAML_LB_SERVERPORT/APP_CONTEXT)
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
   app-a-sp-proxy:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:9cba176d3259deffeb9393b8efc20b78dbd215f4
     ports:
      - "8080:80"
     environment:
      - ENDPOINT_URL=http://app-a:8080/       # Url på applikation (LoginAdaptor), localhost/127.0.0.1 can NOT be used
      - SAML_URL=http://app-a-saml-sp:8080/
      - CONTEXT=appa
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
      - CORRELATION_ID=correlation-id
