version: '2'
services:
   mongo:
     image: mongo:3.3
   app-a-saml-sp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:3bbe0f944ab5ee910ba926e5f30886333e69f61a
     volumes:
      - ./config:/certificates 
     environment:
      - IDP_METADATA_URL=https://medalogin.telesof.kk.dk/auth/realms/medarbejder/protocol/saml/descriptor
      - IDP_LOGIN_URL=https://medalogin.telesof.kk.dk/auth/realms/medarbejder/protocol/saml
      - IDP_METADATA_URL_WGET_OPTIONS=--no-check-certificate
      - CERTIFICATE=/certificates/appa.cert
      - KEY=/certificates/appa.pem
      - SP_ENTITY_ID=dev:kit:appa     
      - SAML_LB_SCHEME=http           # TODO Webserver (LB), http or https
      - SAML_LB_SERVERNAME=localhost  # TODO Webserver (LB), servername
      - SAML_LB_SERVERPORT=8080       # TODO Webserver (LB), Port 
      - APP_CONTEXT=appa              # TODO contexten for applikationen (SAML_LB_SCHEME://SAML_LB_SERVERNAME:SAML_LB_SERVERPORT/APP_CONTEXT)
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
   app-a-sp-proxy:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:3bbe0f944ab5ee910ba926e5f30886333e69f61a
     ports:
      - "8080:80"
     environment:
      - ENDPOINT_URL=http://appa/       # TODO Url på applikation (Login Adaptor) kan være http eller https, localhost/127.0.0.1 can NOT be used.  
      - SAML_URL=http://app-a-saml-sp:8080/
      - CONTEXT=appa
      - REMOVE_CONTEXT=true
      - SET_HOST_SNI=true
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
      - CORRELATION_ID=correlation-id
   appa:
     image: nginx
     ports:
      - "8081:80"
